### ISSUE TITLE
ERROR: System "net.didierverna.clon.termio" not found

### ISSUE THREAD

**Issue by svetlyak40wt** [didierverna/clon#9]
Seems, new CLON is broken. I started to receive this error:

```
System "net.didierverna.clon.termio" not found
   [Condition of type QUICKLISP-CLIENT:SYSTEM-NOT-FOUND]

Restarts:
 0: [CONTINUE] Try again
 1: [ABORT] Give up on "net.didierverna.clon.termio"
 2: [ABORT] Give up on "net.didierverna.clon"
 3: [REGISTER-LOCAL-PROJECTS] Register local projects and try again.
 4: [RETRY] Retry SLY mREPL evaluation request.
 5: [*ABORT] Return to SLY's top level.
 --more--

Backtrace:
 0: ((LABELS QUICKLISP-CLIENT::RECURSE :IN QUICKLISP-CLIENT::COMPUTE-LOAD-STRATEGY) "net.didierverna.clon.termio")
      Locals:
        QL-DIST:NAME = "net.didierverna.clon.termio"
 1: (QL-DIST::CALL-WITH-CONSISTENT-DISTS #<FUNCTION (LAMBDA NIL :IN QUICKLISP-CLIENT::COMPUTE-LOAD-STRATEGY) {10031688CB}>)
      Locals:
        FUN = #<FUNCTION (LAMBDA () :IN QUICKLISP-CLIENT::COMPUTE-LOAD-STRATEGY) {10031688CB}>
 2: (QUICKLISP-CLIENT::COMPUTE-LOAD-STRATEGY "net.didierverna.clon.termio")
      Locals:
        ASDF-SYSTEMS = NIL
        NAME = "net.didierverna.clon.termio"
        QUICKLISP-SYSTEMS = NIL
 3: (QUICKLISP-CLIENT::AUTOLOAD-SYSTEM-AND-DEPENDENCIES "net.didierverna.clon.termio" :PROMPT NIL)
      Locals:
        NAME = "net.didierverna.clon.termio"
        PROMPT = NIL
        TRIED-SO-FAR = #<HASH-TABLE :TEST EQUALP :COUNT 0 {10031687A3}>
 4: (QUICKLISP-CLIENT::AUTOLOAD-SYSTEM-AND-DEPENDENCIES "net.didierverna.clon" :PROMPT NIL)
      Locals:
        NAME = "net.didierverna.clon"
        PROMPT = NIL
        TRIED-SO-FAR = #<HASH-TABLE :TEST EQUALP :COUNT 1 {1001DD0AA3}>
 5: ((:METHOD QL-IMPL-UTIL::%CALL-WITH-QUIET-COMPILATION (T T)) #<unused argument> #<FUNCTION (FLET QUICKLISP-CLIENT::QL :IN QUICKLISP-CLIENT:QUICKLOAD) {1001DD029B}>) [fast-method]
 6: ((:METHOD QL-IMPL-UTIL::%CALL-WITH-QUIET-COMPILATION :AROUND (QL-IMPL:SBCL T)) #<QL-IMPL:SBCL {10023D95F3}> #<FUNCTION (FLET QUICKLISP-CLIENT::QL :IN QUICKLISP-CLIENT:QUICKLOAD) {1001DD029B}>) [fast-m..
 7: ((:METHOD QUICKLISP-CLIENT:QUICKLOAD (T)) :NET.DIDIERVERNA.CLON :PROMPT NIL :SILENT NIL :VERBOSE NIL) [fast-method]
 8: (QL-DIST::CALL-WITH-CONSISTENT-DISTS #<FUNCTION (LAMBDA NIL :IN QUICKLISP-CLIENT:QUICKLOAD) {1001DC8C5B}>)
 9: (SB-INT:SIMPLE-EVAL-IN-LEXENV (QUICKLISP-CLIENT:QUICKLOAD :NET.DIDIERVERNA.CLON) #<NULL-LEXENV>)
10: (EVAL (QUICKLISP-CLIENT:QUICKLOAD :NET.DIDIERVERNA.CLON))
```

### Environment

```
CL-USER> (cl-info:get-cl-info)
OS:   Darwin 19.6.0
Lisp: SBCL 2.1.2
ASDF: 3.3.4.13
QL:   quicklisp 2021-04-11

CL-USER> (cl-info:get-system-info :net.didierverna.clon)
System: NET.DIDIERVERNA.CLON NIL
        /private/tmp/test-clon/.qlot/dists/quicklisp/software/clon-1.0b25/
```

**Comment by svetlyak40wt** [comment]
I also have the same problem with Clon installed from the Github (98e95c0635ec80517711d5e5c2ad43884cbb275f commit).

**Comment by svetlyak40wt** [comment]
The problem is that termio system is missing from `systems.txt` of quicklisp distribution:

```
[art@art-osx:~]% curl -s 'http://beta.quicklisp.org/dist/quicklisp/2021-04-11/systems.txt' | grep 'cl-clon net.didierverna.clon'
cl-clon net.didierverna.clon net.didierverna.clon asdf net.didierverna.clon.core net.didierverna.clon.setup
cl-clon net.didierverna.clon.core net.didierverna.clon.core asdf net.didierverna.clon.setup
cl-clon net.didierverna.clon.setup net.didierverna.clon.setup asdf named-readtables
cl-clon net.didierverna.clon.setup net.didierverna.clon.setup/termio net.didierverna.clon.setup
```

Previous Quicklisp version included this system:

```
[art@art-osx:~]% curl -s 'http://beta.quicklisp.org/dist/quicklisp/2021-02-28/systems.txt' | grep 'cl-clon net.didierverna.clon'
cl-clon net.didierverna.clon net.didierverna.clon asdf net.didierverna.clon.core net.didierverna.clon.setup
cl-clon net.didierverna.clon.core net.didierverna.clon.core asdf net.didierverna.clon.setup
cl-clon net.didierverna.clon.setup net.didierverna.clon.setup asdf
cl-clon net.didierverna.clon.setup net.didierverna.clon.setup/termio net.didierverna.clon.setup
cl-clon net.didierverna.clon.termio net.didierverna.clon.termio asdf net.didierverna.clon.core net.didierverna.clon.setup
```

**Comment by svetlyak40wt** [comment]
Also, there is info from `releases.txt` files:

## New Quickdist 2021-04-11

```
[art@art-osx:~]% curl -s 'http://beta.quicklisp.org/dist/quicklisp/2021-04-11/releases.txt' | grep 'net.didierverna.clon'
cl-clon http://beta.quicklisp.org/archive/cl-clon/2021-04-11/clon-1.0b25.tgz 247117 ff8cb8e1a7988e4d0475a3a51e804f9e 39a0a227047d8afb94f980638e14faef500feccd clon-1.0b25 core/net.didierverna.clon.core.asd demos/advanced.asd demos/simple.asd net.didierverna.clon.asd setup/net.didierverna.clon.setup.asd
```

## Old Quickdist 2021-02-28

```
[art@art-osx:~]% curl -s 'http://beta.quicklisp.org/dist/quicklisp/2021-02-28/releases.txt' | grep 'net.didierverna.clon'
cl-clon http://beta.quicklisp.org/archive/cl-clon/2018-02-28/clon-1.0b24.tgz 191003 7d74fc146a2de5be70a9cb2c5a94312e fa0a4d3ed8bf00ddbdb104b6764a272e21fd0e65 clon-1.0b24 core/net.didierverna.clon.core.asd net.didierverna.clon.asd setup/net.didierverna.clon.setup.asd termio/net.didierverna.clon.termio.asd
```

## Difference

New release includes:

- demos/advanced.asd
- demos/simple.asd

but not 

- termio/net.didierverna.clon.termio.asd

**Comment by svetlyak40wt** [comment]
I've checked and version from the previous Quicklisp release works as expected:

```
CL-USER> (cl-info:get-cl-info)
OS:   Darwin 19.6.0
Lisp: SBCL 2.1.2
ASDF: 3.3.4.13
QL:   cl-clon ql-2021-02-28
      quicklisp 2021-04-11
CL-USER> (cl-info:get-system-info :net.didierverna.clon)
System: NET.DIDIERVERNA.CLON NIL
        /private/tmp/test-clon/.qlot/dists/cl-clon/software/clon-1.0b24/
```

**Comment by svetlyak40wt** [comment]
I've added the latest version of the Clon to the Ultralisp: https://ultralisp.org/projects/didierverna/clon and it works there!

```
CL-USER> (cl-info:get-cl-info)
OS:   Darwin 19.6.0
Lisp: SBCL 2.1.2
ASDF: 3.3.4.13
QL:   quicklisp 2021-04-11
      ultralisp 20210424171500
CL-USER> (cl-info:get-system-info :net.didierverna.clon)
System: NET.DIDIERVERNA.CLON NIL
        /private/tmp/test-clon/.qlot/dists/ultralisp/software/didierverna-clon-20210424171310/
```

**Comment by didierverna** [comment]
Thanks for the report. Indeed, this doesn't seem related to Clon itself. I've opened an issue on Quicklisp controller.

**Comment by mmontone** [comment]
I'm still experiencing this error. Is there any fix? I guess I should avoid Quicklisp for now ...

**Comment by didierverna** [comment]
Hi,

this should now be fixed, but I'll wait for the next Quicklisp release to see if it works (I guess I need to make a new release for Quicklisp to notice tho).

**Comment by gustad** [comment]
Which version of quicklisp includes the fix? I'm having the same issue with what appears to be the most recent version of quicklisp:

```
* (ql:update-client)
The most up-to-date client, version 2021-02-13, is already installed.
T
* (ql:update-dist "quicklisp")

You already have the latest version of "quicklisp": 2022-07-08.
NIL
* (ql:quickload :net.didierverna.clon)
To load "net.didierverna.clon":
  Load 1 ASDF system:
    net.didierverna.clon
; Loading "net.didierverna.clon"

debugger invoked on a QUICKLISP-CLIENT:SYSTEM-NOT-FOUND in thread
#<THREAD "main thread" RUNNING {10027FEE33}>:
  System "net.didierverna.clon.termio" not found

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [CONTINUE               ] Try again
  1: [ABORT                  ] Give up on "net.didierverna.clon.termio"
  2:                           Give up on "net.didierverna.clon"
  3: [REGISTER-LOCAL-PROJECTS] Register local projects and try again.
  4:                           Exit debugger, returning to top level.

((LABELS QUICKLISP-CLIENT::RECURSE :IN QUICKLISP-CLIENT::COMPUTE-LOAD-STRATEGY) "net.didierverna.clon.termio")
0] 1

```

**Comment by didierverna** [comment]
Dammit. I forgot to push the new tag last time, so the new version didn't propagate to quicklisp. Sorry...

**Comment by svetlyak40wt** [comment]
By the way, I'm working on a GitHub action to automate adding a new github tag when a new version is discovered in the ChangeLog. Probably, this automation could be interesting for you too.

**Comment by gustad** [comment]
It does not seem like this has propagated to qucklisp yet. Is there something other than `(ql:update-dist "quicklisp")` which has to be done to obtain the update? The current quicklisp is a bit more recent than above, but the error persist:

```
sbcl --load quicklisp/setup.lisp 
This is SBCL 2.1.3, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
* (ql:update-client)
The most up-to-date client, version 2021-02-13, is already installed.
T
* (ql:update-dist "quicklisp")
You already have the latest version of "quicklisp": 2022-11-07.
NIL
* (ql:quickload :net.didierverna.clon)
To load "net.didierverna.clon":
  Load 1 ASDF system:
    net.didierverna.clon
; Loading "net.didierverna.clon"

debugger invoked on a QUICKLISP-CLIENT:SYSTEM-NOT-FOUND in thread
#<THREAD "main thread" RUNNING {100E538303}>:
  System "net.didierverna.clon.termio" not found

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [CONTINUE               ] Try again
  1: [ABORT                  ] Give up on "net.didierverna.clon.termio"
  2:                           Give up on "net.didierverna.clon"
  3: [REGISTER-LOCAL-PROJECTS] Register local projects and try again.
  4:                           Exit debugger, returning to top level.

((LABELS QUICKLISP-CLIENT::RECURSE :IN QUICKLISP-CLIENT::COMPUTE-LOAD-STRATEGY) "net.didierverna.clon.termio")
   source: (CERROR "Try again" 'SYSTEM-NOT-FOUND :NAME NAME)
0] 
```

**Comment by didierverna** [comment]
Hello ! See two messages above. I forgot to push the latest tag to GitHub, so the latest release was not seen by Quicklisp. It should make its way to the next one, whenever that may be.

Sorry for the inconvenience, and thank you for your patience !

**Comment by didierverna** [comment]
Dammit ! :-( Today's Quicklisp update still doesn't contain the latest release of Clon... I will ping Xach about this.

**Comment by gustad** [comment]
Thank you. I should probably have posted my message in some quicklisp forum and ask why 1.0b26 was not yet included.

**Comment by didierverna** [comment]
I did. Cf. [this issue](https://github.com/quicklisp/quicklisp-controller/issues/20#issuecomment-1431806196).

**Comment by didierverna** [comment]
Clon 1.0b26 is in Quicklisp now, so I'm closing this.
